// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD209vIBd9AHq0JKoACOnTRxwv0LBU29Mk',
    appId: '1:145911937248:web:a11216f35c4cd24cc73885',
    messagingSenderId: '145911937248',
    projectId: 'ga-gold-8b8ee',
    authDomain: 'ga-gold-8b8ee.firebaseapp.com',
    storageBucket: 'ga-gold-8b8ee.firebasestorage.app',
    measurementId: 'G-RX0D61JK7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2HDNOm8zgSM319XaejOvFAdISk8GnNFQ',
    appId: '1:145911937248:android:b97ac6f16591d217c73885',
    messagingSenderId: '145911937248',
    projectId: 'ga-gold-8b8ee',
    storageBucket: 'ga-gold-8b8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJATVMhop5-doPqIjqoUWXZEjoI9lbVo4',
    appId: '1:145911937248:ios:44e05da1d23f9906c73885',
    messagingSenderId: '145911937248',
    projectId: 'ga-gold-8b8ee',
    storageBucket: 'ga-gold-8b8ee.firebasestorage.app',
    iosBundleId: 'com.example.gaFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJATVMhop5-doPqIjqoUWXZEjoI9lbVo4',
    appId: '1:145911937248:ios:44e05da1d23f9906c73885',
    messagingSenderId: '145911937248',
    projectId: 'ga-gold-8b8ee',
    storageBucket: 'ga-gold-8b8ee.firebasestorage.app',
    iosBundleId: 'com.example.gaFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD209vIBd9AHq0JKoACOnTRxwv0LBU29Mk',
    appId: '1:145911937248:web:011154594844134ec73885',
    messagingSenderId: '145911937248',
    projectId: 'ga-gold-8b8ee',
    authDomain: 'ga-gold-8b8ee.firebaseapp.com',
    storageBucket: 'ga-gold-8b8ee.firebasestorage.app',
    measurementId: 'G-HMCYW6V1G9',
  );

}