// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClG3v3CIegjB_SMTd_VJK0k5ZmU74F9ts',
    appId: '1:657796449093:web:212722ce00477a6d5b742c',
    messagingSenderId: '657796449093',
    projectId: 'ga-gold-f010b',
    authDomain: 'ga-gold-f010b.firebaseapp.com',
    storageBucket: 'ga-gold-f010b.firebasestorage.app',
    measurementId: 'G-N5T4G09DCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyINcHQSqt5sMZGgsLCkiEpobWnP_G3hg',
    appId: '1:657796449093:android:5ee16f7ababcd4f75b742c',
    messagingSenderId: '657796449093',
    projectId: 'ga-gold-f010b',
    storageBucket: 'ga-gold-f010b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbpXwfYqaQRjhEpfY-RBdpRhdGbkrl6DQ',
    appId: '1:657796449093:ios:2eeecc97ecbdfc415b742c',
    messagingSenderId: '657796449093',
    projectId: 'ga-gold-f010b',
    storageBucket: 'ga-gold-f010b.firebasestorage.app',
    iosBundleId: 'com.ga.gagold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbpXwfYqaQRjhEpfY-RBdpRhdGbkrl6DQ',
    appId: '1:657796449093:ios:2eeecc97ecbdfc415b742c',
    messagingSenderId: '657796449093',
    projectId: 'ga-gold-f010b',
    storageBucket: 'ga-gold-f010b.firebasestorage.app',
    iosBundleId: 'com.ga.gagold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClG3v3CIegjB_SMTd_VJK0k5ZmU74F9ts',
    appId: '1:657796449093:web:ff83593b020defdf5b742c',
    messagingSenderId: '657796449093',
    projectId: 'ga-gold-f010b',
    authDomain: 'ga-gold-f010b.firebaseapp.com',
    storageBucket: 'ga-gold-f010b.firebasestorage.app',
    measurementId: 'G-1V53CGKS7X',
  );

}